if(total>=270)
        grade='O';
        else if(total>=240)
            grade='E';
            else if(total>=210)
                grade='A';
                else if(total>=180)
                    grade='B';
                    else if(total>=150)
                        grade='c';
                        else if(total>=120)
                            grade='D';
                            else 
                                grade='F';